### ISSUE TITLE
OSX - Dependency on inotify makes it linux only

### ISSUE THREAD

**Issue by hartym** [BernardFW/bernard#69]
I so wanted to try after the talk yesterday but ...

```
$ ./manage.py run
ERROR:bernard.cli:Something bad happened while bootstraping
Traceback (most recent call last):
  File "/Users/rd/.virtualenvs/BernardSandbox/lib/python3.6/site-packages/bernard/cli/_base.py", line 51, in main
    from bernard.server import app
  File "/Users/rd/.virtualenvs/BernardSandbox/lib/python3.6/site-packages/bernard/server/__init__.py", line 2, in <module>
    from .http import app
  File "/Users/rd/.virtualenvs/BernardSandbox/lib/python3.6/site-packages/bernard/server/http.py", line 9, in <module>
    from .views import (
  File "/Users/rd/.virtualenvs/BernardSandbox/lib/python3.6/site-packages/bernard/server/views.py", line 14, in <module>
    from bernard.analytics.base import (
  File "/Users/rd/.virtualenvs/BernardSandbox/lib/python3.6/site-packages/bernard/analytics/__init__.py", line 3, in <module>
    from ._helpers import page_view
  File "/Users/rd/.virtualenvs/BernardSandbox/lib/python3.6/site-packages/bernard/analytics/_helpers.py", line 9, in <module>
    from bernard.engine.state import (
  File "/Users/rd/.virtualenvs/BernardSandbox/lib/python3.6/site-packages/bernard/engine/__init__.py", line 3, in <module>
    from .transition import Transition as Tr
  File "/Users/rd/.virtualenvs/BernardSandbox/lib/python3.6/site-packages/bernard/engine/transition.py", line 16, in <module>
    from .state import (
  File "/Users/rd/.virtualenvs/BernardSandbox/lib/python3.6/site-packages/bernard/engine/state.py", line 9, in <module>
    from bernard.engine.triggers import (
  File "/Users/rd/.virtualenvs/BernardSandbox/lib/python3.6/site-packages/bernard/engine/triggers.py", line 12, in <module>
    from bernard import (
  File "/Users/rd/.virtualenvs/BernardSandbox/lib/python3.6/site-packages/bernard/layers/__init__.py", line 3, in <module>
    from .stack import Stack, stack
  File "/Users/rd/.virtualenvs/BernardSandbox/lib/python3.6/site-packages/bernard/layers/stack.py", line 16, in <module>
    from .definitions import (
  File "/Users/rd/.virtualenvs/BernardSandbox/lib/python3.6/site-packages/bernard/layers/definitions.py", line 12, in <module>
    from bernard.i18n import (
  File "/Users/rd/.virtualenvs/BernardSandbox/lib/python3.6/site-packages/bernard/i18n/__init__.py", line 2, in <module>
    from .translator import Translator, TransText, serialize, unserialize, render
  File "/Users/rd/.virtualenvs/BernardSandbox/lib/python3.6/site-packages/bernard/i18n/translator.py", line 30, in <module>
    from bernard.i18n.loaders import (
  File "/Users/rd/.virtualenvs/BernardSandbox/lib/python3.6/site-packages/bernard/i18n/loaders.py", line 16, in <module>
    import aionotify
  File "/Users/rd/.virtualenvs/BernardSandbox/lib/python3.6/site-packages/aionotify/__init__.py", line 5, in <module>
    from .base import Watcher
  File "/Users/rd/.virtualenvs/BernardSandbox/lib/python3.6/site-packages/aionotify/base.py", line 15, in <module>
    _libc = ctypes.cdll.LoadLibrary('libc.so.6')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libc.so.6, 6): image not found
```

Apparently, it's a "waste of time" (https://github.com/rbarrois/aionotify/issues/5) for aionotify, but any chance Bernard comes to OSX ?

**Comment by Xowap** [comment]
Damn good one, I'll certainly fix that!
