### ISSUE TITLE
Can't install with pip 20.1.1

### ISSUE THREAD

**Issue by rubenbonilla** [BernardFW/bernard#73]
* **Python version:** 3.6.10
* **pip version:** 20.1.1
* **Docker image:** python:3.6-alpine

Hello everyone!

i'm trying to use Bernard in a docker but i can't install bernard inside it because a pip exception:

```
Collecting bernard==0.2.0
  Downloading bernard-0.2.0.tar.gz (97 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-957v4vf8/bernard/setup.py'"'"'; __file__='"'"'/tmp/pip-install-957v4vf8/bernard/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-5yk3kzr6
         cwd: /tmp/pip-install-957v4vf8/bernard/
    Complete output (12 lines):
    Traceback (most recent call last):
      File "/tmp/pip-install-957v4vf8/bernard/setup.py", line 9, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-957v4vf8/bernard/setup.py", line 13, in <module>
        from pip._internal.download import PipSession
    ModuleNotFoundError: No module named 'pip._internal.download'
```

I was looking for download module in [pip Github](https://github.com/pypa/pip/tree/20.1.1/src/pip/_internal) but is not there.

How can i fix this?

Thanks!

**Comment by nmshaikh** [comment]
I ran into the same issue and was able to resolve it by downgrading pip to 9.0.3

`pip install pip==9.0.3`

**Comment by Xowap** [comment]
New packaging should fix most issues in #94
