### ISSUE TITLE
Can't start new project

### ISSUE THREAD

**Issue by jagp8** [BernardFW/bernard#74]
Hello, I've installed bernard in raspbian and the installation gave me no problem, but when I try to start a new project a syntax error appears even when everything seems to be ok

bernard start_project test ~/test                                                                                                                             1 ↵
Traceback (most recent call last):
  File "/usr/local/bin/bernard", line 7, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/bernard/misc/main/_base.py", line 77, in main
    from bernard.misc.start_project import main as main_sp
  File "/usr/local/lib/python3.5/dist-packages/bernard/misc/start_project/__init__.py", line 3, in <module>
    from ._base import main
  File "/usr/local/lib/python3.5/dist-packages/bernard/misc/start_project/_base.py", line 128
    fail(f'Target directory "{target_path}" is not empty')
                                                        ^
SyntaxError: invalid syntax

Well, in the terminal the ^points to the final apostrophe in empty'

**Comment by nilox94** [comment]
The error indicates your Python version doesn't support f-strings, as [this feature](https://peps.python.org/pep-0498/) was introduced in version 3.6.
As of today, to fix this issue, upgrading to Python 3.10 or later should be enough.
I hope this helps!
