### ISSUE TITLE
aiohttp old version breaks project running

### ISSUE THREAD

**Issue by reinaldoq** [BernardFW/bernard#82]
### Issue:

Old version of aiohttp lib is breaking on project run.

`
ERROR:bernard.cli:Something bad happened while bootstraping
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/bernard/cli/_base.py", line 50, in main
from aiohttp import web
File "/usr/local/lib/python3.6/site-packages/aiohttp/__init__.py", line 6, in <module>
from .client import *  # noqa
File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 15, in <module>
from . import connector as connector_mod
File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 13, in <module>
from . import hdrs, helpers
File "/usr/local/lib/python3.6/site-packages/aiohttp/helpers.py", line 716, in <module>
class CeilTimeout(Timeout):
TypeError: function() argument 1 must be code, not str
`
### Solution
This could be solve updating requeriments.txt with `make update`.

**Comment by Xowap** [comment]
This for the issue, #94 will fix these issues
